name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
permissions:      
  contents: write  
jobs:
  build:
    name: Jobs to update datas 
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jfzero1
          svg_out_path: dist/github-contribution-grid-snake.svg

             # Passo 2: DIAGNÓSTICO - Mostra os arquivos criados
      - name: List files in the directory
        run: ls -R

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
